# @package _group_

dpr_wiki:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.wikipedia_split.psgs_w100
  id_prefix: 'wiki:'

dpr_thwiki-20210520_split-300:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file:  /workspace/DPR/downloads/data/thwiki_split_passages/thwiki-20210520_split_newmm-300.tsv
  id_prefix: 'thwiki:'

dpr_thwiki-20210520_split-150:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file:  /workspace/DPR/downloads/data/thwiki_split_passages/thwiki-20210520_split_newmm-150.tsv
  id_prefix: 'thwiki:'

dpr_thwiki-20171217_split-300:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file:  /workspace/DPR/downloads/data/thwiki_split_passages/thwiki-20171217_split_newmm-300.tsv
  id_prefix: 'thwiki_20171217:'

dpr_thwiki-20171217_split-150:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file:  /workspace/DPR/downloads/data/thwiki_split_passages/thwiki-20171217_split_newmm-150.tsv
  id_prefix: 'thwiki_20171217:'