# @package _group_

nq_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.nq-train

nq_train_hn1:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.nq-adv-hn-train

nq_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.nq-dev

trivia_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.trivia-train

trivia_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.trivia-dev

squad1_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.squad1-train

squad1_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.squad1-dev

webq_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.webq-train
  
webq_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.webq-dev
  
curatedtrec_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.curatedtrec-train
  
curatedtrec_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.curatedtrec-dev
    
thwiki_split_w300_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /workspace/DPR/downloads/data/thwiki_split/thwiki-20210520_split_newmm-300/thwiki_split_w300.train.json

thwiki_split_w300_validation:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /workspace/DPR/downloads/data/thwiki_split/thwiki-20210520_split_newmm-300/thwiki_split_w300.validation.json

thwiki_15k_split_w300_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /workspace/DPR/downloads/data/thwiki_split/thwiki-20171217_15k_split_newmm-300/thwiki_15k_split_w300.train.json

thwiki_15k_split_w300_validation:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /workspace/DPR/downloads/data/thwiki_split/thwiki-20171217_15k_split_newmm-300/thwiki_15k_split_w300.validation.json

thwiki_15k_split_w150_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /workspace/DPR/downloads/data/thwiki_split/thwiki-20171217_15k_split_newmm-150/thwiki_15k_split_w150.train.json

thwiki_15k_split_w150_validation:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /workspace/DPR/downloads/data/thwiki_split/thwiki-20171217_15k_split_newmm-150/thwiki_15k_split_w150.validation.json

thwiki_15k_split_w300_hn_bm25_1_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /workspace/DPR/downloads/data/thwiki_split/thwiki-20171217_15k_split_newmm-300_hn-bm25-1/thwiki_15k_split_w300_hn-bm25-1.train.json

thwiki_15k_split_w300_hn_bm25_1_validation:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /workspace/DPR/downloads/data/thwiki_split/thwiki-20171217_15k_split_newmm-300_hn-bm25-1/thwiki_15k_split_w300_hn-bm25-1.validation.json

thwiki_15k_split_w150_hn_bm25_1_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /workspace/DPR/downloads/data/thwiki_split/thwiki-20171217_15k_split_newmm-150_hn-bm25-1/thwiki-_5k_split_w150_hn-bm25-1.train.json

thwiki_15k_split_w150_hn_bm25_1_validation:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /workspace/DPR/downloads/data/thwiki_split/thwiki-20171217_15k_split_newmm-150_hn-bm25-1/thwiki_15k_split_w150_hn-bm25-1.validation.json

thwiki_15k_split_w300_hn_bm25_2_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /workspace/DPR/downloads/data/thwiki_split/thwiki-20171217_15k_split_newmm-300_hn-bm25-2/thwiki_15k_split_w300_hn-bm25-2.train.json

thwiki_15k_split_w300_hn_bm25_2_validation:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /workspace/DPR/downloads/data/thwiki_split/thwiki-20171217_15k_split_newmm-300_hn-bm25-2/thwiki_15k_split_w300_hn-bm25-2.validation.json

thwiki_15k_split_w150_hn_bm25_2_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /workspace/DPR/downloads/data/thwiki_split/thwiki-20171217_15k_split_newmm-150_hn-bm25-2/thwiki_15k_split_w150_hn-bm25-2.train.json

thwiki_15k_split_w150_hn_bm25_2_validation:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /workspace/DPR/downloads/data/thwiki_split/thwiki-20171217_15k_split_newmm-150_hn-bm25-2/thwiki_15k_split_w150_hn-bm25-2.validation.json

thwiki_15k_split_w300_hn_bm25_10_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /workspace/DPR/downloads/data/thwiki_split/thwiki-20171217_15k_split_newmm-300_hn-bm25-10/thwiki_15k_split_w300_hn-bm25-10.train.json

thwiki_15k_split_w300_hn_bm25_10_validation:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /workspace/DPR/downloads/data/thwiki_split/thwiki-20171217_15k_split_newmm-300_hn-bm25-10/thwiki_15k_split_w300_hn-bm25-10.validation.json

thwiki_15k_split_w150_hn_bm25_10_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /workspace/DPR/downloads/data/thwiki_split/thwiki-20171217_15k_split_newmm-150_hn-bm25-10/thwiki_15k_split_w150_hn-bm25-10.train.json

thwiki_15k_split_w150_hn_bm25_10_validation:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /workspace/DPR/downloads/data/thwiki_split/thwiki-20171217_15k_split_newmm-150_hn-bm25-10/thwiki_15k_split_w150_hn-bm25-10.validation.json

thwiki_15k_split_w150_hn_bm25_32_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /workspace/DPR/downloads/data/thwiki_split/thwiki-20171217_15k_split_newmm-150_hn-bm25-32/thwiki_15k_split_w150_hn-bm25-32.train.json

thwiki_15k_split_w150_hn_bm25_32_validation:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /workspace/DPR/downloads/data/thwiki_split/thwiki-20171217_15k_split_newmm-150_hn-bm25-32/thwiki_15k_split_w150_hn-bm25-32.validation.json

thwiki_split_w150_hn_bm25_1_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /workspace/DPR/downloads/data/thwiki_split/thwiki-20210520_split_newmm-150_hn-bm25-1/thwiki_split_w150_hn-bm25-1.train.json

thwiki_split_w150_hn_bm25_1_validation:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /workspace/DPR/downloads/data/thwiki_split/thwiki-20210520_split_newmm-150_hn-bm25-1/thwiki_split_w150_hn-bm25-1.validation.json

thwiki_split_w150_hn_bm25_2_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /workspace/DPR/downloads/data/thwiki_split/thwiki-20210520_split_newmm-150_hn-bm25-2/thwiki_split_w150_hn-bm25-2.train.json

thwiki_split_w150_hn_bm25_2_validation:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /workspace/DPR/downloads/data/thwiki_split/thwiki-20210520_split_newmm-150_hn-bm25-2/thwiki_split_w150_hn-bm25-2.validation.json

thwiki_split_w300_hn_bm25_1_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /workspace/DPR/downloads/data/thwiki_split/thwiki-20210520_split_newmm-300_hn-bm25-1/thwiki_split_w300_hn-bm25-1.train.json

thwiki_split_w300_hn_bm25_1_validation:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /workspace/DPR/downloads/data/thwiki_split/thwiki-20210520_split_newmm-300_hn-bm25-1/thwiki_split_w300_hn-bm25-1.validation.json

thwiki_split_w300_hn_bm25_2_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /workspace/DPR/downloads/data/thwiki_split/thwiki-20210520_split_newmm-300_hn-bm25-2/thwiki_split_w300_hn-bm25-2.train.json

thwiki_split_w300_hn_bm25_2_validation:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /workspace/DPR/downloads/data/thwiki_split/thwiki-20210520_split_newmm-300_hn-bm25-2/thwiki_split_w300_hn-bm25-2.validation.json

thwiki_split_w300_hn_bm25_31_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /workspace/DPR/downloads/data/thwiki_split/thwiki-20210520_split_newmm-300_hn-bm25-31/thwiki_split_w300_hn-bm25-31.train.json

thwiki_split_w300_hn_bm25_31_validation:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /workspace/DPR/downloads/data/thwiki_split/thwiki-20210520_split_newmm-300_hn-bm25-31/thwiki_split_w300_hn-bm25-31.validation.json
