# @package _group_

nq_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.nq-test

nq_train:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.nq-train

nq_dev:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.nq-dev

trivia_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-test

trivia_train:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-train

trivia_dev:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-dev

webq_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.webq-test
  
curatedtrec_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.curatedtrec-test

thwiki_qas_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: /workspace/DPR/downloads/data/thwiki_qas/thwiki-20210520_split_newmm-300/test.csv

thwiki_qas_validation:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: /workspace/DPR/downloads/data/thwiki_qas/thwiki-20210520_split_newmm-300/validation.csv

thwiki_qas_train:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: /workspace/DPR/downloads/data/thwiki_qas/thwiki-20210520_split_newmm-300/train.csv